### PR TITLE
Create pt_br.lang

### PR DESCRIPTION
**Pull request by NaoEoGui**

### CODE REVIEW

**Comment by Sunconure11** [comment]
I would strongly wait on sending PRs, unless otherwise stated. The mod is still in development for 1.18.2.

**Comment by Sunconure11** [comment]
Closing until the mod is more... ready to take in localizations. Sorry.

**Comment by NaoEoGui** [comment]
Hey @Sunconure11, I really hope I can contribute by translating this mod, because I really like it, my favorite Minecraft mod, when it's ready, use my translation or call me and I'll do another one.

**Comment by Sunconure11** [comment]
Noted.

**Pull request closed without merging**
